import datetime
from neo4j_db import create_categories, add_category_to_story, add_story_to_user, create_story, create_user, get_all_categories, get_db, serialize_story
from app import app

with app.app_context():
    db = get_db()
    create_categories()
    print("Creating users...")
    user1 = db.write_transaction(create_user, "Milica", "Petkovic", "milica@elfak.rs", "123")
    user2 = db.write_transaction(create_user, "Maksim", "Petkovic", "maksim@elfak.rs", "123")
    user3 = db.write_transaction(create_user, "Ognjen", "Markovic", "ogi@elfak.rs", "123")
    user4 = db.write_transaction(create_user, "Stefana", "Milosavljevic", "stefana@elfak.rs", "123")
    user5 = db.write_transaction(create_user, "Dimitrije", "Eric", "dimi@elfak.rs", "123")

    print("Created users!")

    print("Creating stories...")
    story1 = db.write_transaction(create_story, title="Lorem Ipsum", text="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis a tellus nec urna tristique rhoncus. Phasellus condimentum felis arcu, ut aliquam mi aliquet sed. Morbi euismod erat non leo fringilla scelerisque. Nulla hendrerit magna vitae nisi consectetur, ac blandit tellus euismod. In cursus velit sit amet ornare pulvinar. Morbi vulputate iaculis mauris, vitae pharetra urna egestas in. Nulla varius dui commodo, cursus felis vitae, faucibus felis. Donec venenatis massa at erat maximus gravida. Etiam aliquam justo dictum metus rhoncus faucibus. Donec ac placerat nulla, ut varius risus. Cras arcu ante, fermentum non lorem sit amet, iaculis congue nisl. Nunc aliquam congue feugiat. Etiam et lorem vitae ipsum scelerisque dignissim.`Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Proin consequat sapien felis, a dignissim justo tristique vel. Suspendisse nec nunc eleifend, ultricies orci eu, interdum tellus. Sed quis condimentum nunc, eu dapibus massa. Mauris mattis dignissim justo, at aliquet nisi dignissim non. Maecenas sit amet tincidunt nisi, nec eleifend velit. Proin ultricies porttitor odio a mattis. Suspendisse eget condimentum mauris. Donec malesuada dolor porta enim aliquam tempor. Donec interdum cursus imperdiet. Duis sit amet ante id ex aliquet condimentum vel id tortor. Curabitur diam nisi, congue vitae consectetur nec, sagittis a mi. Pellentesque ultricies cursus augue ut facilisis. Etiam euismod rhoncus sem eu varius. Aliquam ultricies purus ac tortor eleifend, non malesuada neque dictum. Etiam venenatis pharetra urna at mollis.Integer et aliquam nunc, eget hendrerit libero. Sed viverra tellus ac eros rutrum, eget finibus libero aliquet. Proin tempus consectetur vulputate. Quisque maximus ac odio non pretium. Maecenas et odio quis metus bibendum viverra. Aliquam velit nisl, viverra sit amet faucibus ac, efficitur sed velit. Proin maximus lacinia vestibulum. In aliquet, dolor et luctus dignissim, elit turpis malesuada lorem, et lobortis nibh urna eu lacus. Aliquam posuere eros nec tortor blandit, a tristique dolor ultricies. In massa sem, dapibus vitae lorem rhoncus, finibus euismod est. Phasellus tellus lacus, sollicitudin vel fermentum eu, rutrum vitae ligula. Vivamus non posuere sem. Donec imperdiet a erat sit amet euismod.", \
        grade=0.0, timestamp=datetime.datetime.now())

    story2 = db.write_transaction(create_story, title="Nunc porta condimentum", text="Donec aliquam gravida eleifend. Curabitur ac consequat eros. Morbi molestie viverra ullamcorper. Phasellus viverra placerat ipsum, sit amet euismod urna lobortis ac. Aliquam arcu eros, lacinia vitae sem non, mollis semper sem. Fusce lacinia, risus id bibendum scelerisque, est urna pulvinar neque, id bibendum ligula orci id elit. Pellentesque elementum dolor vitae lectus mollis, a varius dolor vehicula. Nunc lacinia libero quis nibh placerat, et scelerisque tellus imperdiet. Sed eu ornare mi. Vestibulum ex tellus, pellentesque a condimentum ac, ornare ut lectus. Nunc ac pretium felis, in cursus mauris. Nam faucibus semper pellentesque. Praesent hendrerit elit ac augue feugiat dignissim.Integer quis risus eget tortor viverra ultricies. Aliquam blandit iaculis urna, in blandit tellus porttitor ut. Cras sed nisl sed ipsum vehicula bibendum in vel dolor. Aenean convallis libero et nibh ultrices, ut semper augue accumsan. Praesent non bibendum massa, nec porta justo. Quisque eleifend fermentum quam vel cursus. Praesent pulvinar leo est, nec pharetra nibh tempus nec. Mauris non elit rhoncus, tristique ante quis, volutpat lectus. Nunc vitae interdum lectus. Curabitur in augue in urna dapibus dignissim.Sed bibendum lorem id fringilla ullamcorper. Integer nisl ante, eleifend non nibh eget, bibendum consequat enim. Mauris facilisis nisl eget iaculis consectetur. Praesent mattis iaculis elementum. Suspendisse non nulla vitae mauris semper aliquam. Vestibulum molestie augue tristique eros condimentum, scelerisque efficitur quam interdum. Ut dictum, lacus sit amet fringilla interdum, libero enim pulvinar leo, et luctus risus tellus non ligula. Sed ornare libero eget consectetur egestas. Integer interdum lorem vitae felis bibendum, ut tempor sapien maximus.", \
        grade=0.0, timestamp=datetime.datetime.now())

    story3 = db.write_transaction(create_story, title="Aenean ultrices", text="Donec aliquam gravida eleifend. Curabitur ac consequat eros. Morbi molestie viverra ullamcorper. Phasellus viverra placerat ipsum, sit amet euismod urna lobortis ac. Aliquam arcu eros, lacinia vitae sem non, mollis semper sem. Fusce lacinia, risus id bibendum scelerisque, est urna pulvinar neque, id bibendum ligula orci id elit. Pellentesque elementum dolor vitae lectus mollis, a varius dolor vehicula. Nunc lacinia libero quis nibh placerat, et scelerisque tellus imperdiet. Sed eu ornare mi. Vestibulum ex tellus, pellentesque a condimentum ac, ornare ut lectus. Nunc ac pretium felis, in cursus mauris. Nam faucibus semper pellentesque. Praesent hendrerit elit ac augue feugiat dignissim.Integer quis risus eget tortor viverra ultricies. Aliquam blandit iaculis urna, in blandit tellus porttitor ut. Cras sed nisl sed ipsum vehicula bibendum in vel dolor. Aenean convallis libero et nibh ultrices, ut semper augue accumsan. Praesent non bibendum massa, nec porta justo. Quisque eleifend fermentum quam vel cursus. Praesent pulvinar leo est, nec pharetra nibh tempus nec. Mauris non elit rhoncus, tristique ante quis, volutpat lectus. Nunc vitae interdum lectus. Curabitur in augue in urna dapibus dignissim.Sed bibendum lorem id fringilla ullamcorper. Integer nisl ante, eleifend non nibh eget, bibendum consequat enim. Mauris facilisis nisl eget iaculis consectetur. Praesent mattis iaculis elementum. Suspendisse non nulla vitae mauris semper aliquam. Vestibulum molestie augue tristique eros condimentum, scelerisque efficitur quam interdum. Ut dictum, lacus sit amet fringilla interdum, libero enim pulvinar leo, et luctus risus tellus non ligula. Sed ornare libero eget consectetur egestas. Integer interdum lorem vitae felis bibendum, ut tempor sapien maximus.", \
        grade=0.0, timestamp=datetime.datetime.now())

    story4 = db.write_transaction(create_story, title="Praesent elementum", text="Donec aliquam gravida eleifend. Curabitur ac consequat eros. Morbi molestie viverra ullamcorper. Phasellus viverra placerat ipsum, sit amet euismod urna lobortis ac. Aliquam arcu eros, lacinia vitae sem non, mollis semper sem. Fusce lacinia, risus id bibendum scelerisque, est urna pulvinar neque, id bibendum ligula orci id elit. Pellentesque elementum dolor vitae lectus mollis, a varius dolor vehicula. Nunc lacinia libero quis nibh placerat, et scelerisque tellus imperdiet. Sed eu ornare mi. Vestibulum ex tellus, pellentesque a condimentum ac, ornare ut lectus. Nunc ac pretium felis, in cursus mauris. Nam faucibus semper pellentesque. Praesent hendrerit elit ac augue feugiat dignissim.Integer quis risus eget tortor viverra ultricies. Aliquam blandit iaculis urna, in blandit tellus porttitor ut. Cras sed nisl sed ipsum vehicula bibendum in vel dolor. Aenean convallis libero et nibh ultrices, ut semper augue accumsan. Praesent non bibendum massa, nec porta justo. Quisque eleifend fermentum quam vel cursus. Praesent pulvinar leo est, nec pharetra nibh tempus nec. Mauris non elit rhoncus, tristique ante quis, volutpat lectus. Nunc vitae interdum lectus. Curabitur in augue in urna dapibus dignissim.Sed bibendum lorem id fringilla ullamcorper. Integer nisl ante, eleifend non nibh eget, bibendum consequat enim. Mauris facilisis nisl eget iaculis consectetur. Praesent mattis iaculis elementum. Suspendisse non nulla vitae mauris semper aliquam. Vestibulum molestie augue tristique eros condimentum, scelerisque efficitur quam interdum. Ut dictum, lacus sit amet fringilla interdum, libero enim pulvinar leo, et luctus risus tellus non ligula. Sed ornare libero eget consectetur egestas. Integer interdum lorem vitae felis bibendum, ut tempor sapien maximus.", \
        grade=0.0, timestamp=datetime.datetime.now())

    story5 = db.write_transaction(create_story, title="Aliquam erat volutpat", text="Donec aliquam gravida eleifend. Curabitur ac consequat eros. Morbi molestie viverra ullamcorper. Phasellus viverra placerat ipsum, sit amet euismod urna lobortis ac. Aliquam arcu eros, lacinia vitae sem non, mollis semper sem. Fusce lacinia, risus id bibendum scelerisque, est urna pulvinar neque, id bibendum ligula orci id elit. Pellentesque elementum dolor vitae lectus mollis, a varius dolor vehicula. Nunc lacinia libero quis nibh placerat, et scelerisque tellus imperdiet. Sed eu ornare mi. Vestibulum ex tellus, pellentesque a condimentum ac, ornare ut lectus. Nunc ac pretium felis, in cursus mauris. Nam faucibus semper pellentesque. Praesent hendrerit elit ac augue feugiat dignissim.Integer quis risus eget tortor viverra ultricies. Aliquam blandit iaculis urna, in blandit tellus porttitor ut. Cras sed nisl sed ipsum vehicula bibendum in vel dolor. Aenean convallis libero et nibh ultrices, ut semper augue accumsan. Praesent non bibendum massa, nec porta justo. Quisque eleifend fermentum quam vel cursus. Praesent pulvinar leo est, nec pharetra nibh tempus nec. Mauris non elit rhoncus, tristique ante quis, volutpat lectus. Nunc vitae interdum lectus. Curabitur in augue in urna dapibus dignissim.Sed bibendum lorem id fringilla ullamcorper. Integer nisl ante, eleifend non nibh eget, bibendum consequat enim. Mauris facilisis nisl eget iaculis consectetur. Praesent mattis iaculis elementum. Suspendisse non nulla vitae mauris semper aliquam. Vestibulum molestie augue tristique eros condimentum, scelerisque efficitur quam interdum. Ut dictum, lacus sit amet fringilla interdum, libero enim pulvinar leo, et luctus risus tellus non ligula. Sed ornare libero eget consectetur egestas. Integer interdum lorem vitae felis bibendum, ut tempor sapien maximus.", \
        grade=0.0, timestamp=datetime.datetime.now())

    story6 = db.write_transaction(create_story, title="Suspendisse quis nunc", text="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis a tellus nec urna tristique rhoncus. Phasellus condimentum felis arcu, ut aliquam mi aliquet sed. Morbi euismod erat non leo fringilla scelerisque. Nulla hendrerit magna vitae nisi consectetur, ac blandit tellus euismod. In cursus velit sit amet ornare pulvinar. Morbi vulputate iaculis mauris, vitae pharetra urna egestas in. Nulla varius dui commodo, cursus felis vitae, faucibus felis. Donec venenatis massa at erat maximus gravida. Etiam aliquam justo dictum metus rhoncus faucibus. Donec ac placerat nulla, ut varius risus. Cras arcu ante, fermentum non lorem sit amet, iaculis congue nisl. Nunc aliquam congue feugiat. Etiam et lorem vitae ipsum scelerisque dignissim.`Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Proin consequat sapien felis, a dignissim justo tristique vel. Suspendisse nec nunc eleifend, ultricies orci eu, interdum tellus. Sed quis condimentum nunc, eu dapibus massa. Mauris mattis dignissim justo, at aliquet nisi dignissim non. Maecenas sit amet tincidunt nisi, nec eleifend velit. Proin ultricies porttitor odio a mattis. Suspendisse eget condimentum mauris. Donec malesuada dolor porta enim aliquam tempor. Donec interdum cursus imperdiet. Duis sit amet ante id ex aliquet condimentum vel id tortor. Curabitur diam nisi, congue vitae consectetur nec, sagittis a mi. Pellentesque ultricies cursus augue ut facilisis. Etiam euismod rhoncus sem eu varius. Aliquam ultricies purus ac tortor eleifend, non malesuada neque dictum. Etiam venenatis pharetra urna at mollis.Integer et aliquam nunc, eget hendrerit libero. Sed viverra tellus ac eros rutrum, eget finibus libero aliquet. Proin tempus consectetur vulputate. Quisque maximus ac odio non pretium. Maecenas et odio quis metus bibendum viverra. Aliquam velit nisl, viverra sit amet faucibus ac, efficitur sed velit. Proin maximus lacinia vestibulum. In aliquet, dolor et luctus dignissim, elit turpis malesuada lorem, et lobortis nibh urna eu lacus. Aliquam posuere eros nec tortor blandit, a tristique dolor ultricies. In massa sem, dapibus vitae lorem rhoncus, finibus euismod est. Phasellus tellus lacus, sollicitudin vel fermentum eu, rutrum vitae ligula. Vivamus non posuere sem. Donec imperdiet a erat sit amet euismod.", \
        grade=0.0, timestamp=datetime.datetime.now())

    print("Created stories!")

    categories_record = db.read_transaction(get_all_categories)

    all_categories = []
    for cat in categories_record:
        all_categories.append(cat['c'])

    print("Creating relationships...")

    db.write_transaction(add_category_to_story, story1[0]['id'], all_categories[0]['id'])
    db.write_transaction(add_category_to_story, story2[0]['id'], all_categories[1]['id'])
    db.write_transaction(add_category_to_story, story3[0]['id'], all_categories[1]['id'])
    db.write_transaction(add_category_to_story, story4[0]['id'], all_categories[2]['id'])
    db.write_transaction(add_category_to_story, story5[0]['id'], all_categories[0]['id'])
    db.write_transaction(add_category_to_story, story6[0]['id'], all_categories[0]['id'])


    db.write_transaction(add_story_to_user, user1[0]['id'], story1[0]['id'])
    db.write_transaction(add_story_to_user, user1[0]['id'], story2[0]['id'])
    db.write_transaction(add_story_to_user, user2[0]['id'], story3[0]['id'])
    db.write_transaction(add_story_to_user, user3[0]['id'], story4[0]['id'])
    db.write_transaction(add_story_to_user, user4[0]['id'], story5[0]['id'])
    db.write_transaction(add_story_to_user, user5[0]['id'], story6[0]['id'])

    print("Finished")